name: Deploy Infrastructure

on:
  push:
    branches:
      - master
jobs:
  tf_fmt:
    name: Deploy 
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@master

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.13.0
        tf_actions_working_dir: 'terraform'
        tf_actions_subcommand: 'init'
      env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DIGITALOCEAN_TOKEN:  ${{ secrets.DO_TOKEN }}

    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.13.0
        tf_actions_working_dir: 'terraform'
        tf_actions_subcommand: 'validate'

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.13.0
        tf_actions_working_dir: 'terraform'
        tf_actions_subcommand: 'apply'
        args: '-var=drone_github_client_id=${{ secrets.DRONE_GITHUB_CLIENT_ID }} -var=drone_github_client_secret=${{ secrets.drone_github_client_secret }} -var=DRONE_RPC_SECRET=${{ secrets.drone_rpc_secret }} -var=drone_server_host=${{ secrets.drone_server_host }}'
      env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DIGITALOCEAN_TOKEN:  ${{ secrets.DO_TOKEN }}

